require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DbTemplatesController do

  # This should return the minimal set of attributes required to create a valid
  # DbTemplate. As you add validations to DbTemplate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      :body => "<%= 'Hi from DbTemplate!' %>",
      :path => "posts/index",
      :format => "html",
      :locale => "en",
      :handler => "erb",
      :partial => false
    }
  end

  describe "GET index" do
    it "assigns all db_templates as @db_templates" do
      db_template = DbTemplate.create! valid_attributes
      get :index
      assigns(:db_templates).should eq([db_template])
    end
  end

  describe "GET show" do
    it "assigns the requested db_template as @db_template" do
      db_template = DbTemplate.create! valid_attributes
      get :show, :id => db_template.id.to_s
      assigns(:db_template).should eq(db_template)
    end
  end

  describe "GET new" do
    it "assigns a new db_template as @db_template" do
      get :new
      assigns(:db_template).should be_a_new(DbTemplate)
    end
  end

  describe "GET edit" do
    it "assigns the requested db_template as @db_template" do
      db_template = DbTemplate.create! valid_attributes
      get :edit, :id => db_template.id.to_s
      assigns(:db_template).should eq(db_template)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DbTemplate" do
        expect {
          post :create, :db_template => valid_attributes
        }.to change(DbTemplate, :count).by(1)
      end

      it "assigns a newly created db_template as @db_template" do
        post :create, :db_template => valid_attributes
        assigns(:db_template).should be_a(DbTemplate)
        assigns(:db_template).should be_persisted
      end

      it "redirects to the created db_template" do
        post :create, :db_template => valid_attributes
        response.should redirect_to(DbTemplate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved db_template as @db_template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DbTemplate.any_instance.stub(:save).and_return(false)
        post :create, :db_template => {}
        assigns(:db_template).should be_a_new(DbTemplate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DbTemplate.any_instance.stub(:save).and_return(false)
        post :create, :db_template => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested db_template" do
        db_template = DbTemplate.create! valid_attributes
        # Assuming there are no other db_templates in the database, this
        # specifies that the DbTemplate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DbTemplate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => db_template.id, :db_template => {'these' => 'params'}
      end

      it "assigns the requested db_template as @db_template" do
        db_template = DbTemplate.create! valid_attributes
        put :update, :id => db_template.id, :db_template => valid_attributes
        assigns(:db_template).should eq(db_template)
      end

      it "redirects to the db_template" do
        db_template = DbTemplate.create! valid_attributes
        put :update, :id => db_template.id, :db_template => valid_attributes
        response.should redirect_to(db_template)
      end
    end

    describe "with invalid params" do
      it "assigns the db_template as @db_template" do
        db_template = DbTemplate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DbTemplate.any_instance.stub(:save).and_return(false)
        put :update, :id => db_template.id.to_s, :db_template => {}
        assigns(:db_template).should eq(db_template)
      end

      it "re-renders the 'edit' template" do
        db_template = DbTemplate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DbTemplate.any_instance.stub(:save).and_return(false)
        put :update, :id => db_template.id.to_s, :db_template => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested db_template" do
      db_template = DbTemplate.create! valid_attributes
      expect {
        delete :destroy, :id => db_template.id.to_s
      }.to change(DbTemplate, :count).by(-1)
    end

    it "redirects to the db_templates list" do
      db_template = DbTemplate.create! valid_attributes
      delete :destroy, :id => db_template.id.to_s
      response.should redirect_to(db_templates_url)
    end
  end

end
